//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mט1EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ID { get; set; }
        public Nullable<int> ClientNumber { get; set; }
        public Nullable<int> ProductNumber { get; set; }
        public Nullable<int> QuantityReserved { get; set; }
        public Nullable<double> TotalPriceOfResevation { get; set; }
    }
}
